### ISSUE TITLE
Classpath issues if APOC is declared in .jqassistant.yml

### ISSUE THREAD

**Issue by DirkMahler** [kontext-e/jqassistant-gradle-plugin#16]
jQA allows declaration of additional Neo4j plugins in `.jqassistant.yml`, a typical one is APOC:

```
jqassistant:
  store:
    embedded:
      neo4j-plugins:
        - group-id: org.neo4j.procedure
          artifact-id: apoc-core
          classifier: core
          version: ${neo4j-apoc.version}      
```

This works with the jQA Maven plugin as well as with the "pure" CLI but currently fails with the Gradle plugin.

The reason for that is a restriction of Neo4j which requires plugins to be available via the application classloader (just dropping the artifacts into the Neo4j plugin folder sadly is not enough). Therefore the jQA CLI extends the classpath using the Java Instrumentation API, relying on an according declaration in the JAR manifest, see https://github.com/jQAssistant/jqassistant/blob/master/cli/neo4jv5/pom.xml#L35. As far as I can see the Gradle plugin runs the CLI directly by referencing the Main class but bypassing that declaration. 

I'd like to discuss an effective solution about howto make the resolved plugin artifacts available on the classpath. This does not necessarily means to use the instrumentation mechanism, I am open to find more elegant solutions.
